type store = u32

variant error {
  store-table-full,
  store-not-found,
  invalid-store,
  no-such-key,
  runtime(string)
}

open: func(name: string) -> expected<store, error>

get: func(store: store, key: string) -> expected<list<u8>, error>

set: func(store: store, key: string, value: list<u8>) -> expected<unit, error>

delete: func(store: store, key: string) -> expected<unit, error>

exists: func(store: store, key: string) -> expected<bool, error>

close: func(store: store)
