[package]
name = "cloud-kv"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
pbjson-types = "0.5"
tokio = { version = "1", features = ["rt"] }
tokio-stream = "0.1"
tonic = "0.8"
tracing = "0.1"

kv = { git = "ssh://git@github.com/fermyon/mynosql.git" }
